[package]
name = "archive-subtract"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
clap = { version = "4.5.9", features = ["cargo"] }
decompress = "0.6.0"
pathdiff = "0.2.1"
thiserror = "1.0.62"
uuid = { version = "1.10.0", features = ["v4", "fast-rng"] }
walkdir = "2.5.0"
